### PR TITLE
update attachment test for issue/#90

### PR DESCRIPTION
**Pull request by giovino**
creating a test for a failed attachment submission documented
in issue/#90.

### CODE REVIEW

**Comment by wesyoung** [comment]
part of this; paperclip sees through your spoof

http://stackoverflow.com/questions/22966481/paperclip-gem-spoofing-error

it sees you're trying to pass it a .txt and it's really an email, so the error isn't that it doesn't detect the text bits, but it's actually figuring out it's an email file.

 in the future, with properly formatted email msgs, use .eml 

found a work-around will roll out.

**Comment by giovino** [comment]
that's interesting ```^From:``` at the beginning of a text file makes it:

```
$ file text.txt 
text.txt: news or mail, ASCII text
```

i wonder if this should be a feature of the csirtg SDK.. if you are going to submit a file.. we know the API expects file extensions to match the content-type.

**Comment by wesyoung** [comment]
probably can't be done. unix mime != redhat mime != paperclip spoofing technology... so most of the time you probably won't know till we get to the end of the chain...

**Comment by giovino** [comment]
so what's the answer.. have the API (paperclip) stamp it with whatever it likes?

**Comment by wesyoung** [comment]
i dunno yet; don't have a large enough sample set to see where the cracks are...

**Comment by giovino** [comment]
I suspect we can use Virustotal as an example to follow. 

I downloaded and renamed putty.exe to putty.txt and uploaded that file to VT. 

https://www.virustotal.com/en/file/b10922648f6ad71f3f20b9acdfacf9aeff706cad6c52737cdc426307ccfa51d9/analysis/1455886946/

1. vt takes the file with the .txt extension
2. vt stamps it the file type as: ```File type Win32 EXE```
3. you can see that file has been uploaded with many different filenames / extensions

```
File names
unconfirmed 632568.crdownload
putty.exe.wtwbsk7.partial
putty_orig - copy.exe
putty.exe.dzatq0f.partial
putty (2).exe
562245_1b204f_putty.exe
putty.exe
putty.exe.uj3b975.partial
putty(2).exe
f82d5681-1ca9-353e-56d9-0503a4c27ccb
putty.exe.nbo7da9.partial
putty-v66beta_wait.exe
is-tv6cc.tmp
unconfirmed 751732.crdownload
putty.exe
putty.exe.v09otbi.partial
putty (3).exe
putty_beta_0_66.exe
putty (8).exe
unconfirmed 613881.crdownload
putty.exe.bak
putty_.exe
2016_01_07_19_15_18.000787
putty.exe
is-lp2p1.tmp
```

**Comment by wesyoung** [comment]
does vt allow you to dl the files at all? (i'm not seeing it in the doc)

**Comment by giovino** [comment]
Yes if you use the paid for API

https://www.virustotal.com/en/documentation/private-api/#file-download

**Pull request merged**
